---
title: "Comparison with IPO"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ipo-comparison}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# libraries
suppressPackageStartupMessages({
  # library(IPO2)
  devtools::load_all()
  library(xcms)
})

# parallel processing
register(BiocParallel::MulticoreParam(stop.on.error = FALSE))
```

# Introduction

The goal of this vignette is to compare the results from IPO and IPO2 as well as to assess overall performance/efficiency.

# Setup

```{r}
mzml_file <- file.path(find.package("msdata"), "microtofq/MM14.mzML")
mzml_data <- MSnbase::readMSData(files = mzml_file, mode = "onDisk")
```

# IPO 

```{r}
ipo_params <- IPO::getDefaultXcmsSetStartingParams()
ipo_params$mzdiff <- -0.001
ipo_params$ppm <- 56
ipo_params$min_peakwidth <- c(3, 9.5)
ipo_params$max_peakwidth <- c(10, 20)

bench::mark(
  ipo_result <- 
    IPO::optimizeXcmsSet(
      mzml_file, 
      ipo_params, 
      plot = FALSE, 
      subdir = NULL, 
      nSlaves = 0, 
      BPPARAM = bpparam()
    ), 
  memory = FALSE
)
```

# IPO2

```{r}
ipo2_params <- IPO2:::suggest_centwave_params()
ipo2_params$mzdiff <- -0.001
ipo2_params$ppm <- 56
ipo2_params$min_peakwidth <- c(3, 9.5)
ipo2_params$max_peakwidth <- c(10, 20)
ipo2_params$prefilter_int <- 100

bench::mark(
  ipo2_result <- 
    IPO2::optimize_centwave(
      raw_data = mzml_data, 
      parameter_list = ipo2_params
    ), 
  memory = FALSE
)
```

# Compare Results

For this model fitting task, IPO2 is ~3 times faster. Both sessions complete the same number of iterations (2). The selected optimal parameters differ among the two approaches: 

```{r}
ipo_min <- ipo_result$best_settings$parameters$min_peakwidth
ipo_max <- ipo_result$best_settings$parameters$max_peakwidth

ipo2_min <- ipo2_result$history[score == max(score)]$min_peakwidth
ipo2_max <- ipo2_result$history[score == max(score)]$max_peakwidth

tibble::tribble(
  ~package, ~min_peakwidth, ~max_peakwidth, 
  "IPO", ipo_min, ipo_max, 
  "IPO2", ipo2_min, ipo2_max
)
```

