---
title: "Parameter Optimization with IPO2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{parameter-optimization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# libraries
suppressPackageStartupMessages({
  devtools::load_all()
  library(xcms)
  # library(IPO2)
})

# parallel processing
doParallel::registerDoParallel(parallel::detectCores() - 1)
```

# Data Import

```{r}
files <- 
  list.files(
    system.file("extdata", package = "IPO2"), 
    full.names = TRUE
  )

raw_data <- 
  MSnbase::readMSData(files = files[[1]], mode = "onDisk") %>% 
  MSnbase::filterRt(c(300, 900))
```

# Optimize Peak Picking

```{r}
# cleanup
unlink(
  list.files(
    system.file("scratch", package = "IPO2"), 
    c("centwave"), 
    full.names = TRUE
  ), 
  recursive = TRUE
)

cwp_params <-
  xfun::cache_rds(
    optimize_centwave(
      raw_data = raw_data,
      plot_dir = system.file("scratch", package = "IPO2"),
      log_file = paste0(system.file("scratch", package = "IPO2"), "/centwave_log.txt")
    ),
    file = "cwp_params.rds",
    rerun = TRUE
  )
```

# Optimize Retention Time and Grouping

```{r}
raw_data <- 
  MSnbase::readMSData(files = files[seq(2, 18, 3)], mode = "onDisk") %>% 
  MSnbase::filterRt(c(300, 900))
```

```{r}
xcmsnexp <- 
  xfun::cache_rds(
    xcms::findChromPeaks(
      raw_data,
      param = cwp_params$best_cwp,
      BPPARAM = BiocParallel::SerialParam(),
    ), 
    file = "xcmsnexp.rds", 
    rerun = FALSE
  )
```

```{r}
# cleanup
unlink(
  list.files(
    system.file("scratch", package = "IPO2"), 
    c("align_group"), 
    full.names = TRUE
  ), 
  recursive = TRUE
)

align_group_params <-
  xfun::cache_rds(
    optimize_align_group(
      xcmsnexp = xcmsnexp,
      plot_dir = system.file("scratch", package = "IPO2"),
      log_file = paste0(system.file("scratch", package = "IPO2"), "/align_group_log.txt")
    ), 
    file = "align_group_params.rds",
    rerun = TRUE
  )
```



